FileVersion = 1

[Project]
Name = "StormTactics.Core"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Serialization" = "*"
"Sedulous.Serialization.Xml" = "*"
"Sedulous.Xml" = "*"
