FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Engine.Audio" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.Engine.UI" = "*", "Sedulous.Physics.Jolt" = "*", "Sedulous.Audio.SDL3" = "*", "Sedulous.Audio.Decoders" = "*", "Sedulous.Geometry" = "*", "Sedulous.Profiler" = "*", "Sedulous.Drawing" = "*", "Sedulous.Drawing.Fonts" = "*", "Sedulous.Drawing.Renderer" = "*", "Sedulous.Fonts" = "*"}

[Project]
Name = "ImpactArena"
StartupObject = "ImpactArena.Program"
