FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Drawing" = "*", "Sedulous.Fonts" = "*", corlib = "*"}

[Project]
Name = "Sedulous.UI"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Program"
