FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Validation" = "*", "Sedulous.RHI.DX12" = "*", "Sedulous.RHI.Vulkan" = "*", SampleFramework = "*"}

[Project]
Name = "Sample018_Bindless"
StartupObject = "Sample018_Bindless.Program"
