FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Animation" = "*", "Sedulous.Animation.Resources" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*", "Sedulous.Runtime" = "*"}

[Project]
Name = "Sedulous.Engine.Animation"
