FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Foundation" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Animation" = "*", "Sedulous.Animation.Resources" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.Animation"
TargetType = "BeefLib"
