FileVersion = 1

[Project]
Name = "GUISandbox"
StartupObject = "GUISandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Imaging" = "*"
"Sedulous.Imaging.SDL" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.GUI" = "*"
"Sedulous.GUI.Shell" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts.TTF" = "*"
