FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.RHI" = "*", SampleFramework = "*", "cimgui-Beef" = "*"}

[Project]
Name = "ImGuiSample"
StartupObject = "ImGuiSample.Program"
