FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*", "Sedulous.Drawing" = "*", "Sedulous.GUI" = "*"}

[Project]
Name = "Sedulous.Editor.Core"
