FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*"}

[Project]
Name = "RHIBlending"
StartupObject = "RHIBlending.Program"
