FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Validation" = "*", "Sedulous.RHI.DX12" = "*", "Sedulous.RHI.Vulkan" = "*", SampleFramework = "*"}

[Project]
Name = "Sample004_Compute"
StartupObject = "Sample004_Compute.Program"
