FileVersion = 1

[Project]
Name = "Sedulous.Runtime.Client"
TargetType = "BeefLib"
StartupObject = "Sedulous.Runtime.Client.Program"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.DX12" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Serialization.OpenDDL" = "*"
