FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Animation" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Core" = "*", "Sedulous.Animation.Resources" = "*", "Sedulous.Geometry.Resources" = "*", "Sedulous.Imaging" = "*", "Sedulous.Materials.Resources" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Render" = "*", "Sedulous.Resources" = "*", "Sedulous.Textures.Resources" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.Render"
TargetType = "BeefLib"
