FileVersion = 1

[Project]
Name = "StormTactics.Tests"
TargetType = "BeefTest"

[Dependencies]
corlib = "*"
"StormTactics.Core" = "*"
"StormTactics.Battle" = "*"
"StormTactics.Game" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Serialization" = "*"
"Sedulous.Serialization.Xml" = "*"
"Sedulous.Xml" = "*"
