FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Physics" = "*", "Sedulous.Render" = "*", "Sedulous.Profiler" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.Physics"
TargetType = "BeefLib"
