FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Render" = "*", corlib = "*", recastnavigation-Beef = "*", "Sedulous.Serialization" = "*", "Sedulous.Runtime" = "*"}

[Project]
Name = "Sedulous.Engine.Navigation"
