FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.GUI" = "*", "Sedulous.GUI.Shell" = "*", "Sedulous.Drawing.Renderer" = "*", "Sedulous.Drawing" = "*", "Sedulous.RHI" = "*", "Sedulous.Shell" = "*", "Sedulous.Render" = "*", "Sedulous.Profiler" = "*", "Sedulous.Shaders" = "*", "Sedulous.Serialization" = "*", "Sedulous.RenderGraph" = "*"}

[Project]
Name = "Sedulous.Engine.UI"
