FileVersion = 1

[Project]
Name = "Sedulous.Engine.UI"

[Dependencies]
corlib = "*"
"Sedulous.Engine.Scenes" = "*"
"Sedulous.Engine.Input" = "*"
"Sedulous.Engine.Render" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.GUI" = "*"
"Sedulous.GUI.Shell" = "*"
"Sedulous.GUI.Runtime" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Render" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Serialization" = "*"
corlib = "*"
