FileVersion = 1

[Project]
Name = "DrawingSandbox"
StartupObject = "DrawingSandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Imaging" = "*"
"Sedulous.RHI" = "*"
"Sedulous.RHI.Vulkan" = "*"
"Sedulous.RHI.Validation" = "*"
"Sedulous.Shell.SDL3" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.Shaders" = "*"
