FileVersion = 1

[Project]
Name = "Sedulous.Runtime"
TargetType = "BeefLib"
StartupObject = "Sedulous.Runtime.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core.Logging" = "*"
"Sedulous.Jobs" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Resources" = "*"
