FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Net" = "*", "Sedulous.Net.HTTP" = "*"}

[Project]
Name = "NetWebSocket"
TargetType = "BeefConsoleApplication"
StartupObject = "NetWebSocket.Program"
