FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Net" = "*", "Sedulous.Net.HTTP" = "*", "Sedulous.Foundation.Logging" = "*"}

[Project]
Name = "NetHttpClient"
StartupObject = "NetHttpClient.Program"
