FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Scenes" = "*", "Sedulous.Framework.Input" = "*", "Sedulous.Framework.Render" = "*", "Sedulous.Foundation" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.GUI" = "*", "Sedulous.GUI.Shell" = "*", "Sedulous.Drawing.Renderer" = "*", "Sedulous.Drawing" = "*", "Sedulous.RHI" = "*", "Sedulous.Shell" = "*", "Sedulous.Render" = "*", "Sedulous.Profiler" = "*", "Sedulous.Shaders" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Framework.UI"
