FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Profiler" = "*", "Sedulous.Serialization" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.OpenDDL" = "*", "Sedulous.Foundation.Mathematics.Serialization" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "Sedulous.Framework.Scenes"
TargetType = "BeefLib"
