FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Runtime.Client" = "*"}

[Project]
Name = "RenderScene"
StartupObject = "RenderScene.Program"
