FileVersion = 1

[Project]
Name = "Sedulous.Drawing"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Core.Logging" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.ImageData" = "*"
