FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Animation" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Core" = "*", "Sedulous.Serialization" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.OpenDDL" = "*"}

[Project]
Name = "Sedulous.Animation.Tests"
TargetType = "BeefTest"
