FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Materials" = "*", "Sedulous.Runtime.Client" = "*"}

[Project]
Name = "RenderMultiView"
StartupObject = "RenderMultiView.Program"
