FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Framework.Runtime" = "*"}

[Project]
Name = "RenderGeometry"
StartupObject = "RenderGeometry.Program"
