FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Tools.Core" = "*", "Sedulous.AppFramework" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*", "Sedulous.Models.FBX" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Drawing" = "*", "Sedulous.Render" = "*", "Sedulous.Materials" = "*", "Sedulous.Materials.Resources" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Animation" = "*", "Sedulous.Animation.Resources" = "*", "Sedulous.Textures" = "*", "Sedulous.Textures.Resources" = "*", "Sedulous.Imaging" = "*", "Sedulous.Imaging.SDL" = "*", "Sedulous.Imaging.STB" = "*"}

[Project]
Name = "Sedulous.Tools.ModelViewer"
StartupObject = "Sedulous.Tools.ModelViewer.Program"
