FileVersion = 1

[Project]
Name = "Sedulous.GUI.Runtime"

[Dependencies]
corlib = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core" = "*"
"Sedulous.GUI" = "*"
"Sedulous.GUI.Shell" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Drawing.Renderer" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Profiler" = "*"
"Sedulous.Fonts.TTF" = "*"
