FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Scenes" = "*", "Sedulous.Framework.Render" = "*", "Sedulous.Framework.Physics" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Render" = "*", corlib = "*", recastnavigation-Beef = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Framework.Navigation"
