FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Runtime.Client" = "*"}

[Project]
Name = "RenderDecals"
StartupObject = "RenderDecals.Program"
