FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.Shaders" = "*", "Sedulous.VG" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.ImageData" = "*"}

[Project]
Name = "Sedulous.VG.Renderer"
TargetType = "BeefLib"
