FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Runtime.Client" = "*", "Sedulous.GUI" = "*", "Sedulous.GUI.Runtime" = "*", "Sedulous.Fonts" = "*"}

[Project]
Name = "RenderWater"
StartupObject = "RenderWater.Program"
