FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Profiler" = "*"}

[Project]
Name = "FrameworkRender"
StartupObject = "FrameworkRender.Program"
