FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.UI" = "*", "Sedulous.UI.Toolkit" = "*", "Sedulous.Drawing" = "*", "Sedulous.Fonts" = "*", corlib = "*"}

[Project]
Name = "Sedulous.UI.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Tests.Program"
