FileVersion = 1

[Project]
Name = "Sedulous.UI.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.Toolkit" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Fonts" = "*"
corlib = "*"
