FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Runtime.Client" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Engine.Physics" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.Engine.Navigation" = "*", "Sedulous.GUI.Runtime" = "*", "Sedulous.Physics.Jolt" = "*", "Sedulous.Geometry" = "*", "Sedulous.Profiler" = "*", "Sedulous.Drawing.Fonts" = "*", corlib = "*"}

[Project]
Name = "EngineNavigation"
StartupObject = "EngineNavigation.Program"
