FileVersion = 1

[Project]
Name = "Sedulous.Drawing.Renderer"

[Dependencies]
corlib = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Drawing" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Profiler" = "*"
