FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Engine.Input" = "*", "Sedulous.GUI" = "*", "Sedulous.GUI.Shell" = "*", "Sedulous.Drawing.Renderer" = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.Renderer" = "*", "Sedulous.Drawing" = "*", "Sedulous.Serialization" = "*", "Sedulous.Shell" = "*", "Sedulous.Logging" = "*", "Sedulous.Shaders" = "*"}

[Project]
Name = "Sedulous.Engine.UI"
