FileVersion = 1

[Project]
Name = "RenderCinematic"
StartupObject = "RenderCinematic.Program"
DefaultNamespace = "RenderCinematic"

[Dependencies]
corlib = "*"
"Sedulous.Render" = "*"
"Sedulous.Geometry" = "*"
"Sedulous.Geometry.Tooling" = "*"
"Sedulous.Geometry.Tooling.Resources" = "*"
"Sedulous.Models.GLTF" = "*"
"Sedulous.Imaging" = "*"
"Sedulous.Imaging.SDL" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.GUI" = "*"
"Sedulous.GUI.Runtime" = "*"
"Sedulous.Fonts" = "*"
corlib = "*"
