FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Tools.AppFramework" = "*", "Sedulous.Editor.Core" = "*", "Sedulous.Drawing" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Logging" = "*"}

[Project]
Name = "Sedulous.Editor.App"
