FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Core" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Shell" = "*"}

[Project]
Name = "Sedulous.Engine.Input"
TargetType = "BeefLib"
