FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.GUI" = "*", "Sedulous.GUI.Shell" = "*", "Sedulous.Drawing.Fonts" = "*", "Sedulous.Drawing.Renderer" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Drawing" = "*", "Sedulous.Fonts" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Shaders" = "*"}

[Project]
Name = "Sedulous.AppFramework"
TargetType = "BeefLib"
StartupObject = "Sedulous.AppFramework.Program"
