FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Shaders" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Runtime.Client" = "*", "Sedulous.Render" = "*", "Sedulous.RenderGraph" = "*"}

[Project]
Name = "RenderTriangle"
StartupObject = "RenderTriangle.Program"
