FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Shaders" = "*", "Sedulous.Core.Mathematics" = "*", "Sedulous.Runtime.Client" = "*", "Sedulous.Render" = "*"}

[Project]
Name = "RenderTriangle"
StartupObject = "RenderTriangle.Program"
