FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Imaging" = "*", "Sedulous.Imaging.SDL" = "*", "Sedulous.Imaging.STB" = "*", "Sedulous.Engine.Runtime" = "*"}

[Project]
Name = "RenderSky"
StartupObject = "RenderSky.Program"
