FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Imaging" = "*", "Sedulous.Imaging.SDL" = "*", "Sedulous.Imaging.STB" = "*", "Sedulous.Runtime.Client" = "*", "Sedulous.Runtime" = "*"}

[Project]
Name = "RenderSky"
StartupObject = "RenderSky.Program"
