FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Runtime.Client" = "*"}

[Project]
Name = "RenderParticles"
StartupObject = "RenderParticles.Program"
