FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Editor.Core" = "*", "Sedulous.Engine.Scenes" = "*", "Sedulous.Engine.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.GUI" = "*", "Sedulous.Foundation.Mathematics" = "*", "Sedulous.Foundation" = "*", "Sedulous.Serialization" = "*", "Sedulous.Xml" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "Sedulous.Editor.Scenes"
TargetType = "BeefLib"
